site_name: SAGE Research Lab
site_author: SAGE Lab Members
copyright: '©2021 SAGE Research Lab'

nav:
  - Home: index.md
  - Research Projects: research.md
  - Publications: publications.md
  - Team: team.md
  - Contact: contact.md


theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  logo: 'images/sage-logo.png'
  favicon: 'images/sage-logo.png'

  features:
    - navigation.tabs

  palette:

 - scheme: slate
    primary: 'green'
    accent: 'light green'
    toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Toggle Light Mode
  - scheme: gmu
    toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    #Toggle Dark Mode
 

plugins:
    - search
    - encryptcontent:
        title_prefix: '[Protected]'
        summary: 'This Content is Password Protected'
        placeholder: 'Click here to type the Password, then press Enter'
        decryption_failure_message: 'Invalid Password'
        encryption_info_message: 'This course content is password protected. Please enter the password.'


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      toc_depth: 3
  - attr_list
  - meta

extra:
  generator: false