site_name: SAGE Research Lab
site_author: SAGE Lab Members
copyright: '©2021 SAGE Research Lab'

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Team: team.md


theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  logo: 'images/sage-logo.png'
  favicon: 'images/sage-logo.png'
  font: false

  icon:
    admonition:
      success: fontawesome/solid/rss-square
      tip: fontawesome/solid/file-alt
      example: fontawesome/solid/tools
      note: fontawesome/solid/book
      abstract: fontawesome/solid/database


  features:
    - navigation.tabs

  palette:

    # Toggle Light Mode
  - media: "(prefers-color-scheme: light)"
    scheme: gmu
    toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    #Toggle Dark Mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: 'green'
    accent: 'light green'
    toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
    - search
    - encryptcontent:
        title_prefix: '[Protected]'
        summary: 'This Content is Password Protected'
        placeholder: 'Click here to type the Password, then press Enter'
        decryption_failure_message: 'Invalid Password'
        encryption_info_message: 'This course content is password protected. Please enter the password.'


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      toc_depth: 3
  - attr_list
  - meta

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sageselab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sageselab